# Categorical Manipulation

### Loading Libraries

In [68]:
# Numerical Computing
import numpy as np

# Data Manipulation
import pandas as pd

# Data Visualisation
import seaborn as sns
import matplotlib.pyplot as plt

# OS
import requests
from io import StringIO

#### Retrieving Data

In [2]:
pd.set_option('display.max_rows', 10)

In [3]:
# url = 'https://github.com/mattharrison/datasets/raw/master/data/'\
#     'siena2018-pres.csv'

In [4]:
url = 'https://github.com/mattharrison/datasets/raw/master/data/' \
      'vehicles.csv.zip'

In [5]:
df = pd.read_csv(url, engine='pyarrow', dtype_backend='pyarrow')

In [6]:
make = df.make

In [7]:
make

0        Alfa Romeo
1           Ferrari
2             Dodge
3             Dodge
4            Subaru
            ...
41139        Subaru
41140        Subaru
41141        Subaru
41142        Subaru
41143        Subaru
Name: make, Length: 41144, dtype: string[pyarrow]

#### Frequency Counts

In [8]:
make.value_counts()

make
Chevrolet                           4003
Ford                                3371
Dodge                               2583
GMC                                 2494
Toyota                              2071
                                    ...
Grumman Allied Industries              1
Environmental Rsch and Devp Corp       1
General Motors                         1
Goldacre                               1
Isis Imports Ltd                       1
Name: count, Length: 136, dtype: int64[pyarrow]

In [9]:
make.shape, make.nunique()

((41144,), 136)

#### Beneficts of Categories

In [10]:
cat_make = make.astype('category')

In [11]:
make.memory_usage(deep=True)

425767

In [12]:
cat_make.memory_usage(deep=True)

84533

In [13]:
%%timeit
cat_make.str.upper()

334 μs ± 2.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [14]:
%%timeit
make.str.upper()

414 μs ± 2.01 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [15]:
old_make = make.astype(str)

In [16]:
%%timeit
old_make.str.upper()

428 μs ± 3.47 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

#### Conversion to Ordinal Categories

In [17]:
make_type = pd.CategoricalDtype(
    categories=sorted(make.unique()), ordered=True)

In [18]:
ordered_make = make.astype(make_type)

ordered_make

0        Alfa Romeo
1           Ferrari
2             Dodge
3             Dodge
4            Subaru
            ...
41139        Subaru
41140        Subaru
41141        Subaru
41142        Subaru
41143        Subaru
Name: make, Length: 41144, dtype: category
Categories (136, str): ['AM General' < 'ASC Incorporated' < 'Acura' < 'Alfa Romeo' ... 'Volvo' < 'Wallace Environmental' < 'Yugo' < 'smart']

In [19]:
(make
    .astype('category')
    .cat.as_ordered()
)

0        Alfa Romeo
1           Ferrari
2             Dodge
3             Dodge
4            Subaru
            ...
41139        Subaru
41140        Subaru
41141        Subaru
41142        Subaru
41143        Subaru
Name: make, Length: 41144, dtype: category
Categories (136, string[pyarrow]): [AM General < ASC Incorporated < Acura < Alfa Romeo ... Volvo < Wallace Environmental < Yugo < smart]

In [20]:
ordered_make.max()

'smart'

In [21]:
cat_make.max()

TypeError: Categorical is not ordered for operation max
you can use .as_ordered() to change the Categorical to an ordered one

In [22]:
ordered_make.sort_values()

20288    AM General
20289    AM General
369      AM General
358      AM General
19314    AM General
            ...
31289         smart
31290         smart
29605         smart
22974         smart
26882         smart
Name: make, Length: 41144, dtype: category
Categories (136, str): ['AM General' < 'ASC Incorporated' < 'Acura' < 'Alfa Romeo' ... 'Volvo' < 'Wallace Environmental' < 'Yugo' < 'smart']

#### The `.cat` Accesor

In [23]:
cat_make.cat.rename_categories(
    [c.lower() for c in cat_make.cat.categories])

0        alfa romeo
1           ferrari
2             dodge
3             dodge
4            subaru
            ...
41139        subaru
41140        subaru
41141        subaru
41142        subaru
41143        subaru
Name: make, Length: 41144, dtype: category
Categories (136, str): ['am general', 'asc incorporated', 'acura', 'alfa romeo', ..., 'volvo', 'wallace environmental', 'yugo', 'smart']

In [24]:
ordered_make.cat.rename_categories(
    {c:c.lower() for c in ordered_make.cat.categories})

0        alfa romeo
1           ferrari
2             dodge
3             dodge
4            subaru
            ...
41139        subaru
41140        subaru
41141        subaru
41142        subaru
41143        subaru
Name: make, Length: 41144, dtype: category
Categories (136, str): ['am general' < 'asc incorporated' < 'acura' < 'alfa romeo' ... 'volvo' < 'wallace environmental' < 'yugo' < 'smart']

In [25]:
ordered_make.cat.reorder_categories(
    sorted(cat_make.cat.categories, key=str.lower))

0        Alfa Romeo
1           Ferrari
2             Dodge
3             Dodge
4            Subaru
            ...
41139        Subaru
41140        Subaru
41141        Subaru
41142        Subaru
41143        Subaru
Name: make, Length: 41144, dtype: category
Categories (136, str): ['Acura' < 'Alfa Romeo' < 'AM General' < 'American Motors Corporation' ... 'Volvo' < 'VPG' < 'Wallace Environmental' < 'Yugo']

#### Category Gotchas

In [26]:
(ordered_make
    .head(100)
    .value_counts()
)

make
Dodge                          17
Ford                            8
Oldsmobile                      8
Buick                           7
Chevrolet                       5
                               ..
Vixen Motor Company             0
Volga Associated Automobile     0
Wallace Environmental           0
Yugo                            0
smart                           0
Name: count, Length: 136, dtype: int64

In [27]:
(cat_make
    .head(100)
    .groupby(cat_make.head(100), observed=False)
    .first()
)

make
AM General                           <NA>
ASC Incorporated                     <NA>
Acura                                <NA>
Alfa Romeo                     Alfa Romeo
American Motors Corporation          <NA>
                                  ...
Volkswagen                     Volkswagen
Volvo                               Volvo
Wallace Environmental                <NA>
Yugo                                 <NA>
smart                                <NA>
Name: make, Length: 136, dtype: category
Categories (136, string[pyarrow]): [AM General, ASC Incorporated, Acura, Alfa Romeo, ..., Volvo, Wallace Environmental, Yugo, smart]

In [28]:
(make
    .head(100)
    .groupby(make.head(100))
    .first()
)

make
Alfa Romeo          Alfa Romeo
Audi                      Audi
BMW                        BMW
Buick                    Buick
CX Automotive    CX Automotive
                     ...
Rolls-Royce        Rolls-Royce
Subaru                  Subaru
Toyota                  Toyota
Volkswagen          Volkswagen
Volvo                    Volvo
Name: make, Length: 25, dtype: string[pyarrow]

In [29]:
(cat_make
    .head(100)
    .groupby(cat_make.head(100), observed=True)
    .first()
)

make
Alfa Romeo          Alfa Romeo
Audi                      Audi
BMW                        BMW
Buick                    Buick
CX Automotive    CX Automotive
                     ...
Rolls-Royce        Rolls-Royce
Subaru                  Subaru
Toyota                  Toyota
Volkswagen          Volkswagen
Volvo                    Volvo
Name: make, Length: 25, dtype: category
Categories (136, string[pyarrow]): [AM General, ASC Incorporated, Acura, Alfa Romeo, ..., Volvo, Wallace Environmental, Yugo, smart]

In [30]:
ordered_make.iloc[0]

'Alfa Romeo'

In [31]:
ordered_make.iloc[[0]]

0    Alfa Romeo
Name: make, dtype: category
Categories (136, str): ['AM General' < 'ASC Incorporated' < 'Acura' < 'Alfa Romeo' ... 'Volvo' < 'Wallace Environmental' < 'Yugo' < 'smart']

#### Generalization

In [32]:
def generalize_topn(ser, n=5, other='Other'):
    topn = ser.value_counts().index[:n]
    if isinstance(ser.dtype, pd.CategoricalDtype):
        ser = ser.cat.set_categories(
            topn.set_categories(list(topn) + [other]))
    return ser.where(ser.isin(topn), other)

In [33]:
cat_make.pipe(generalize_topn, n=20, other='NA')

0            NA
1            NA
2         Dodge
3         Dodge
4        Subaru
          ...
41139    Subaru
41140    Subaru
41141    Subaru
41142    Subaru
41143    Subaru
Name: make, Length: 41144, dtype: category
Categories (21, str): ['Chevrolet', 'Ford', 'Dodge', 'GMC', ..., 'Volvo', 'Hyundai', 'Chrysler', 'NA']

In [34]:
def generalize_mapping(ser, mapping, default):
    seen = None
    res = ser.astype(str)
    for old, new in mapping.items():
        mask = ser.str.contains(old)
        if seen is None:
            seen = mask
        else:
            seen |= mask
        res = res.where(~mask, new)
    res = res.where(seen, default)
    return res.astype('category')

In [35]:
generalize_mapping(cat_make, {
    'Ford':'US', 'Tesla':'US',
    'Chevrolet':'US', 'Dodge':'US',
    'Oldsmobile':'US', 'Plymouth':'US',
    'BMW':'German'}, 'Other')

0        Other
1        Other
2           US
3           US
4        Other
         ...
41139    Other
41140    Other
41141    Other
41142    Other
41143    Other
Name: make, Length: 41144, dtype: category
Categories (3, str): ['German', 'Other', 'US']

# Dataframes

#### A Simple Python Version

In [36]:
df = {
    'index': [0, 1, 2],
    'cols': [
        {'name':'growth',
         'data': [.5, .7, 1.2]},
        {'name':'Name',
         'data':['Paul', 'George', 'Ringo']},
    ]
}

In [37]:
def get_row(df, idx):
    results = []
    value_idx = df['index'].index(idx)
    for col in df['cols']:
        results.append(col['data'][value_idx])
    return results

In [38]:
get_row(df, 1)

[0.7, 'George']

In [39]:
def get_col(df, name):
    for col in df['cols']:
        if col['name'] == name:
            return col['data']

In [40]:
get_col(df, 'Name')

['Paul', 'George', 'Ringo']

#### Dataframes

In [41]:
df = pd.DataFrame({
    'growth': [.5, .7, 1.2],
    'Name': ['Paul', 'George', 'Ringo']})

In [42]:
print(df)

   growth    Name
0     0.5    Paul
1     0.7  George
2     1.2   Ringo

In [43]:
df.iloc[2]

growth      1.2
Name      Ringo
Name: 2, dtype: object

In [44]:
df['Name']

0      Paul
1    George
2     Ringo
Name: Name, dtype: str

In [45]:
type(df['Name'])

pandas.Series

In [46]:
df['Name'].str.lower()

0      paul
1    george
2     ringo
Name: Name, dtype: str

#### Construction

In [47]:
print(pd.DataFrame([
    {'growth':.5, 'Name': 'Paul'},
    {'growth':.7, 'Name': 'George'},
    {'growth':1.2, 'Name': 'Ringo'}]))

   growth    Name
0     0.5    Paul
1     0.7  George
2     1.2   Ringo

In [48]:
csv_file = StringIO("""growth, Name
    .5, Paul
    .7, George
    1.2, Ringo
""")

In [49]:
print(pd.read_csv(csv_file, dtype_backend='pyarrow', engine='pyarrow'))

   growth     Name
0     0.5     Paul
1     0.7   George
2     1.2    Ringo

In [50]:
np.random.seed(42)

print(pd.DataFrame(np.random.randn(10, 3),
                  columns=['a', 'b', 'c']))

          a         b         c
0  0.496714 -0.138264  0.647689
1  1.523030 -0.234153 -0.234137
2  1.579213  0.767435 -0.469474
3  0.542560 -0.463418 -0.465730
4  0.241962 -1.913280 -1.724918
5 -0.562288 -1.012831  0.314247
6 -0.908024 -1.412304  1.465649
7 -0.225776  0.067528 -1.424748
8 -0.544383  0.110923 -1.150994
9  0.375698 -0.600639 -0.291694

#### Dataframe Axis

In [52]:
df.axes

[RangeIndex(start=0, stop=3, step=1), Index(['growth', 'Name'], dtype='str')]

In [53]:
df.sum(axis=0)

growth                2.4
Name      PaulGeorgeRingo
dtype: object

In [54]:
df.sum(axis=1)

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [55]:
df.sum(axis='index')

growth                2.4
Name      PaulGeorgeRingo
dtype: object

In [56]:
# df.sum(axis=1)

In [57]:
df.axes[0]

RangeIndex(start=0, stop=3, step=1)

In [58]:
df.axes[1]

Index(['growth', 'Name'], dtype='str')

In [60]:
df = pd.DataFrame({'Score1': [None, None],
                   'Score2': [85, 90]})

In [61]:
print(df)

  Score1  Score2
0   None      85
1   None      90

In [62]:
df.apply(np.sum, axis=0)

Score1      0
Score2    175
dtype: int64

# Similarities with Series & DataFrames

### Getting Data

In [77]:
url = 'https://en.wikipedia.org/wiki/'\
'Historical_rankings_of_presidents_of_the_United_States'

In [78]:
# pres_dfs = pd.read_html(url, dtype_backend='pyarrow')

In [79]:
headers = {

    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)"

}

response = requests.get(url, headers=headers)

response.raise_for_status()

In [80]:
pres_dfs = pd.read_html(StringIO(response.text), dtype_backend="pyarrow")

In [81]:
pres_dfs

[             Seq. [b][c]             President        Political party  \
 0                      1     George Washington            Independent
 1                      2            John Adams             Federalist
 2                      3      Thomas Jefferson  Democratic-Republican
 3                      4         James Madison  Democratic-Republican
 4                      5          James Monroe  Democratic-Republican
 ..                   ...                   ...                    ...
 41                    43        George W. Bush             Republican
 42                    44          Barack Obama             Democratic
 43              45/47[b]          Donald Trump             Republican
 44                    46             Joe Biden             Democratic
 45  Total surveyed[b][c]  Total surveyed[b][c]   Total surveyed[b][c]

     APSA 2024[27][26]  Siena 2022[32] C-SPAN 2021[20] Siena 2018[33]  \
 0                   3               3               2              1
 1                  13              16              15             14
 2                   5               5               7              5
 3                  11              10              16              7
 4                  18              12              12              8
 ..                ...             ...             ...            ...
 41                 32              35              29             33
 42                  7              11              10             17
 43                 45              43              41             42
 44                 14              19               –              –
 45                 45              45              44             44

    APSA 2018[26] C-SPAN 2017[17] PHN 2016[24]  ... C-SPAN 2000 Schl. 1996[5]  \
 0              2               2            3  ...           3       2 (tie)
 1             14              19           10  ...          16            11
 2              5               7            5  ...           7             4
 3             12              17           15  ...          18            17
 4             18              13           14  ...          14            15
 ..           ...             ...          ...  ...         ...           ...
 41            30              33           34  ...           –             –
 42             8              12            7  ...           –             –
 43            44               –            –  ...           –             –
 44             –               –            –  ...           –             –
 45            44              43           41  ...          41            39

    R-McI 1996[39] Siena 1994 Siena 1990 Siena 1982 CT 1982 M-B 1982  \
 0               3          4          4          4       2        3
 1              14         12         14         10      15        9
 2               4          5          3          2       5        4
 3              10          9          8          9      17       14
 4              13         15         11         15      16       15
 ..            ...        ...        ...        ...     ...      ...
 41              –          –          –          –       –        –
 42              –          –          –          –       –        –
 43              –          –          –          –       –        –
 44              –          –          –          –       –        –
 45             41         41         40         39      36       36

    Schl. 1962[4] Schl. 1948
 0              2          2
 1             10          9
 2              5          5
 3             12         14
 4             18         12
 ..           ...        ...
 41             –          –
 42             –          –
 43             –          –
 44             –          –
 45            31         29

 [46 rows x 28 columns],
       0                                                  1
 0  None  This section relies excessively on references ...,
    Rank     Liberals (n = 190) Conservatives (n = 50)
 0     1        Abraham Lincoln        Abraham Lincoln
 1     2  Franklin D. Roosevelt      George Washington
 2     3      George Washington  Franklin D. Roosevelt
 3     4       Thomas Jefferson       Thomas Jefferson
 4     5     Theodore Roosevelt     Theodore Roosevelt
 ..  ...                    ...                    ...
 13   32         James Buchanan        Franklin Pierce
 14   33         Andrew Johnson         Andrew Johnson
 15   34       Ulysses S. Grant         James Buchanan
 16   35          Richard Nixon       Ulysses S. Grant
 17   36      Warren G. Harding      Warren G. Harding

 [18 rows x 3 columns],
    Seq.          President        Political party  Bg  PL  CAb  RC  CAp  HE  \
 0     1  George Washington            Independent   7  18   12   3    3   4
 1     2         John Adams             Federalist   4  29   18  26   10  13
 2     3   Thomas Jefferson  Democratic-Republican   1   4    6   4    6  16
 3     4      James Madison  Democratic-Republican   3  10   11   9    7  12
 4     5       James Monroe  Democratic-Republican   9  12   15   8   14   9
 ..  ...                ...                    ...  ..  ..  ...  ..  ...  ..
 38   40      Ronald Reagan             Republican  34   5    5   7   31  21
 39   41  George H. W. Bush             Republican  11  27   33  23   34  32
 40   42       Bill Clinton             Democratic  22  11    8  25   11   3
 41   43     George W. Bush             Republican  36  23   42  32   41  42
 42   44       Barack Obama             Democratic  32  21    7  18   13  17

      L  ...  Im  DA  Int  EAb  FPA  LA  IQ  AM  EV   O
 0    1  ...   9   4    2    2    3   1  12   1   3   4
 1   23  ...  17  22    3   19   12  20   7  15  12  17
 2    6  ...   3   6   14    5    7   6   1   6   5   5
 3   17  ...   8  12    5   14   20  17   2  10   8   6
 4    9  ...  16   8   10   11    2  13  15   7   9   7
 ..  ..  ...  ..  ..  ...  ...  ...  ..  ..  ..  ..  ..
 38   3  ...  18  23   26   20   13   8  36  13  17  18
 39  26  ...  31  28   20   22   14  22  24  18  22  22
 40  10  ...  10  10   41   15   18  14   9  34  15  13
 41  18  ...  40  38   39   39   42  38  42  38  39  39
 42  16  ...   6  16   12   16   22  16   8  21  18  15

 [43 rows x 24 columns],
    Seq.          President        Political party        VSA         DL  \
 0     1  George Washington            Independent   5 (8.22)   4 (7.78)
 1     2         John Adams             Federalist  13 (6.33)  17 (5.56)
 2     3   Thomas Jefferson  Democratic-Republican   3 (8.29)   6 (7.57)
 3     4      James Madison  Democratic-Republican  15 (6.23)  15 (5.78)
 4     5       James Monroe  Democratic-Republican  18 (5.97)  18 (5.55)
 ..  ...                ...                    ...        ...        ...
 38   40      Ronald Reagan             Republican   6 (8.17)  11 (6.28)
 39   41  George H. W. Bush             Republican  31 (4.04)  27 (4.24)
 40   42       Bill Clinton             Democratic  14 (6.28)  10 (6.46)
 41   43     George W. Bush             Republican  21 (5.64)  28 (4.22)
 42   44       Barack Obama             Democratic  11 (7.00)  11 (6.44)

           FPL         MA         HL           O
 0    2 (7.89)   1 (9.20)   3 (9.18)   3 (84.5%)
 1   11 (7.05)   9 (7.15)  12 (6.26)  12 (64.7%)
 2    8 (7.14)   8 (7.16)   4 (8.16)   4 (76.6%)
 3   19 (5.75)  11 (6.72)  10 (6.38)  14 (61.7%)
 4    9 (7.08)  12 (6.27)  14 (6.18)  13 (62.1%)
 ..        ...        ...        ...         ...
 38  10 (7.06)  14 (5.89)  15 (5.89)   8 (66.6%)
 39  13 (6.64)  15 (5.87)  22 (4.71)  22 (51.0%)
 40  16 (6.39)  34 (3.48)  16 (5.57)  19 (56.4%)
 41  38 (3.82)  33 (3.55)  35 (2.75)  31 (39.6%)
 42  19 (6.04)   8 (7.27)   8 (6.66)   8 (66.8%)

 [43 rows x 9 columns],
    Seq.          President        Political party        VSA         DL  \
 0     1  George Washington            Independent   3 (8.46)   4 (7.65)
 1     2         John Adams             Federalist  18 (6.27)  14 (5.98)
 2     3   Thomas Jefferson  Democratic-Republican   4 (8.38)   6 (7.20)
 3     4      James Madison  Democratic-Republican  15 (6.36)  13 (6.08)
 4     5       James Monroe  Democratic-Republican  14 (6.40)  16 (5.80)
 ..  ...                ...                    ...        ...        ...
 38   40      Ronald Reagan             Republican   6 (8.19)  15 (5.86)
 39   41  George H. W. Bush             Republican  26 (4.83)  26 (4.67)
 40   42       Bill Clinton             Democratic  13 (6.88)   7 (6.93)
 41   43     George W. Bush             Republican  25 (4.93)  32 (3.83)
 42   44       Barack Obama             Democratic  10 (7.39)   9 (6.71)

           FPL         MA         HL          O
 0    3 (7.69)   2 (8.90)   3 (8.94)   3 (8.33)
 1   11 (6.79)  11 (6.79)  10 (6.47)  10 (6.52)
 2    9 (6.83)  10 (6.82)   4 (7.65)   5 (7.38)
 3   20 (5.79)  12 (6.47)  13 (6.36)  15 (6.21)
 4    8 (7.02)  14 (6.16)  14 (6.20)  14 (6.32)
 ..        ...        ...        ...        ...
 38  12 (6.72)  17 (5.64)  19 (5.51)  13 (6.38)
 39  10 (6.81)  15 (5.68)  20 (5.41)  21 (5.48)
 40  14 (6.35)  34 (3.22)  16 (5.85)  19 (5.85)
 41  39 (2.94)  35 (2.91)  37 (2.60)  34 (3.44)
 42  15 (6.30)   4 (7.86)   5 (7.44)   7 (7.14)

 [43 rows x 9 columns],
    Seq.          President        Political party  PP  CL  EM  MA  IR  AS  RC  \
 0     1  George Washington            Independent   4   2   1   1   2   2   2
 1     2         John Adams             Federalist  22  17  15  11  13  21  24
 2     3   Thomas Jefferson  Democratic-Republican   8  13  13   6  11   7   5
 3     4      James Madison  Democratic-Republican  18  19  19   9  22  17  13
 4     5       James Monroe  Democratic-Republican  17  14  18  16   7  11   9
 ..  ...                ...                    ...  ..  ..  ..  ..  ..  ..  ..
 38   40      Ronald Reagan             Republican   5   8  16  13   9  33   8
 39   41  George H. W. Bush             Republican  23  12  21  17   8  16  15
 40   42       Bill Clinton             Democratic   9  18   3  38  18  20  17
 41   43     George W. Bush             Republican  25  25  36  34  41  34  25
 42   44       Barack Obama             Democratic  10  15   8   7  24  19  39

     VSA  PEJ  PCT   O
 0     2   13    1   2
 1    20   15   19  19
 2     5   17    6   7
 3    18   18   16  17
 4    14   25   11  13
 ..  ...  ...  ...  ..
 38    6   23    8   9
 39   27   16   20  20
 40   19    6   17  15
 41   26   19   35  33
 42   12    3   15  12

 [43 rows x 14 columns],
    Seq.          President        Political party  Bg        Im  Int  IQ   L  \
 0     1  George Washington            Independent   7         7    1  10   1
 1     2         John Adams             Federalist   3        14    4   4  24
 2     3   Thomas Jefferson  Democratic-Republican   2         2   14   1   8
 3     4      James Madison  Democratic-Republican   4         6    7   3  16
 4     5       James Monroe  Democratic-Republican   9        15   11  18   6
 ..  ...                ...                    ...  ..       ...  ...  ..  ..
 39   41  George H. W. Bush             Republican  10        28   18  19  20
 40   42       Bill Clinton             Democratic  21        13   39   8  11
 41   43     George W. Bush             Republican  17        30   33  41  21
 42   44       Barack Obama             Democratic  25  11 (tie)   13   9  15
 43   45       Donald Trump             Republican  44        41   44  44  10

           WR  AC  ...  PL  RC  CAp  HE  EAp  DA  FPA  AM  EV   O
 0          6   2  ...  18   1    1   1    1   2    2   1   2   1
 1         14  32  ...  28  17    4  13   15  19   13  16  10  14
 2          5  14  ...   5   5    7  20    4   6    9   7   5   5
 3         15   6  ...   9  10    6  14    7  11   19  11   8   7
 4         16   7  ...  12   8   11   9    9  10    5   6   9   8
 ..       ...  ..  ...  ..  ..  ...  ..  ...  ..  ...  ..  ..  ..
 39  27 (tie)  13  ...  21  20   29  28   19  26   10  17  21  21
 40        17   3  ...  13  18   10   5   12   9   18  30  14  15
 41        20  29  ...  19  22   28  36   29  30   38  36  34  33
 42        23  16  ...  23  31   14  10   13  13   20  10  11  17
 43        25  43  ...  43  43   40  39   44  40   42  41  42  42

 [44 rows x 24 columns],
    Seq.          President        Political party  PP  CL  EM  MA  IR  AS  RC  \
 0     1  George Washington            Independent   4   2   2   2   2   2   1
 1     2         John Adams             Federalist  22  18  10   8  14  19  22
 2     3   Thomas Jefferson  Democratic-Republican   7   8  11  11  11   6   5
 3     4      James Madison  Democratic-Republican  19  19  20  12  22  16  12
 4     5       James Monroe  Democratic-Republican  17  14  17  14   6  10   9
 ..  ...                ...                    ...  ..  ..  ..  ..  ..  ..  ..
 39   41  George H. W. Bush             Republican  25  10  23  15   8  13  17
 40   42       Bill Clinton             Democratic  10  20   5  38  19  22  23
 41   43     George W. Bush             Republican  23  22  35  26  38  33  21
 42   44       Barack Obama             Democratic   9  17   9   6  21  14  32
 43   45       Donald Trump             Republican  32  41  34  44  43  44  42

     VSA  PEJ  PCT   O
 0     2   14    2   2
 1    20   13   18  15
 2     6   20    6   7
 3    15   21   12  16
 4    14   25   11  12
 ..  ...  ...  ...  ..
 39   28   15   21  21
 40   19    8   20  19
 41   25   18   29  29
 42   12    3   10  10
 43   36   40   42  41

 [44 rows x 14 columns],
    Seq.          President        Political party attributes                  \
    Seq.          President        Political party         Bg  Im Int  IQ   L
 0     1  George Washington            Independent          6   6   3  12   1
 1     2         John Adams             Federalist          5  16   5   4  26
 2     3   Thomas Jefferson  Democratic-Republican          7   4  20   2   5
 3     4      James Madison  Democratic-Republican          4   7   9   3  13
 4     5       James Monroe  Democratic-Republican         13  15  16  21   8
 ..  ...                ...                    ...        ...  ..  ..  ..  ..
 40   42       Bill Clinton             Democratic         19  12  40   9  10
 41   43     George W. Bush             Republican         20  35  34  41  23
 42   44       Barack Obama             Democratic         18   7   6   7  14
 43   45       Donald Trump             Republican         45  43  45  45  17
 44   46          Joe Biden             Democratic         15  22  12  27  34

        abilities  ... accomplishments                             average
     WR        AC  ...              PL  RC CAp  HE EAp  DA FPA  AM      PV   O
 0    5         3  ...              18   3   1   4   1   4   2   1       3   3
 1   20        35  ...              31  33   8  15  17  18  17  20      14  16
 2    8        14  ...               4   5  11  20   7   6  10   8       7   5
 3   15        11  ...              10  10  14  19  11  13  20  11      11  10
 4   14         7  ...              17   9  15  12  13   9   6   6      12  12
 ..  ..       ...  ...             ...  ..  ..  ..  ..  ..  ..  ..     ...  ..
 40  17         4  ...              13  18   7   5  14  12  18  33      13  14
 41  22        32  ...              21  22  34  39  37  34  41  38      35  35
 42  21        10  ...              19  27   9  10   8  10  19   9       8  11
 43  23        44  ...              32  42  43  41  45  43  45  43      44  43
 44  24         9  ...              25  31  10  14  10  19  21  16      20  19

 [45 rows x 24 columns],
     Rank Overall (performance + diversity and inclusion score)  \
 0      1                     Franklin D. Roosevelt (83/100)
 1      2                              Barack Obama (77/100)
 2      3                         Lyndon B. Johnson (69/100)
 3      4                              Bill Clinton (62/100)
 4      5                           John F. Kennedy (61/100)
 ..   ...                                                ...
 9     10                         George H. W. Bush (49/100)
 10    11                               Gerald Ford (39/100)
 11    12                            George W. Bush (38/100)
 12    13                             Richard Nixon (32/100)
 13    14                              Donald Trump (11/100)

    Diversity and inclusion leadership score only
 0                          Barack Obama (75/100)
 1                          Bill Clinton (54/100)
 2                          Jimmy Carter (43/100)
 3                        George W. Bush (41/100)
 4                     Lyndon B. Johnson (40/100)
 ..                                           ...
 9                       Harry S. Truman (28/100)
 10                      Ronald Reagan (27.8/100)
 11                 Dwight D. Eisenhower (26/100)
 12                        Richard Nixon (24/100)
 13                          Donald Trump (9/100)

 [14 rows x 3 columns],
       0                                                  1
 0  None  This section relies excessively on references ...,
                President Outstanding Above average Average Below average Poor  \
 0   Dwight D. Eisenhower         10%           39%     36%            2%   1%
 1        John F. Kennedy         18%           56%     19%            2%   1%
 2      Lyndon B. Johnson          4%           16%     46%           14%   8%
 3          Richard Nixon          2%           13%     27%           29%  23%
 4            Gerald Ford          2%           14%     56%           15%   5%
 ..                   ...         ...           ...     ...           ...  ...
 6          Ronald Reagan         19%           42%     27%            6%   4%
 7      George H. W. Bush          3%           24%     48%           12%  10%
 8           Bill Clinton         11%           44%     29%            9%   6%
 9         George W. Bush          3%           18%     36%           20%  23%
 10          Barack Obama          6%           22%     31%           18%  22%

    No opinion  Weighted average[a]
 0         12%                 3.63
 1          4%                 3.92
 2         12%                 2.93
 3          6%                 2.38
 4          8%                 2.92
 ..        ...                  ...
 6          2%                 3.67
 7          2%                 2.98
 8          1%                 3.45
 9          1%                 2.58
 10         1%                 2.72

 [11 rows x 8 columns],
            President Outstanding Above average Average Below average Poor  \
 0    John F. Kennedy         23%           47%     25%            2%   1%
 1      Richard Nixon          4%            7%     26%           29%  30%
 2       Jimmy Carter          6%           21%     43%           14%  10%
 3      Ronald Reagan         17%           35%     30%           10%   6%
 4  George H. W. Bush          7%           21%     53%           11%   6%
 5       Bill Clinton         10%           26%     37%           16%  11%
 6     George W. Bush          6%           18%     49%           16%  10%
 7       Barack Obama         21%           35%     22%           11%  12%
 8       Donald Trump          9%           20%     10%           14%  47%

    Weighted average[a]
 0                 3.83
 1                 2.14
 2                 2.81
 3                 3.41
 4                 3.06
 5                 3.08
 6                 2.91
 7                 3.45
 8                  2.3  ,
            President Outstanding Above average Average Below average Poor  \
 0  Lyndon B. Johnson          3%           18%     31%           10%   9%
 1      Richard Nixon          4%           13%     26%           22%  20%
 2       Jimmy Carter         10%           23%     27%           13%  13%
 3      Ronald Reagan         24%           23%     20%           11%  10%
 4  George H. W. Bush          4%           19%     40%           15%  10%

In [82]:
df = pres_dfs[2]

In [83]:
df

   Rank     Liberals (n = 190) Conservatives (n = 50)
0     1        Abraham Lincoln        Abraham Lincoln
1     2  Franklin D. Roosevelt      George Washington
2     3      George Washington  Franklin D. Roosevelt
3     4       Thomas Jefferson       Thomas Jefferson
4     5     Theodore Roosevelt     Theodore Roosevelt
..  ...                    ...                    ...
13   32         James Buchanan        Franklin Pierce
14   33         Andrew Johnson         Andrew Johnson
15   34       Ulysses S. Grant         James Buchanan
16   35          Richard Nixon       Ulysses S. Grant
17   36      Warren G. Harding      Warren G. Harding

[18 rows x 3 columns]

In [85]:
for i, table in enumerate(pres_dfs):
    print(i, table.columns)

0 Index(['Seq. [b][c]', 'President', 'Political party', 'APSA 2024[27][26]',
       'Siena 2022[32]', 'C-SPAN 2021[20]', 'Siena 2018[33]', 'APSA 2018[26]',
       'C-SPAN 2017[17]', 'PHN 2016[24]', 'APSA 2015[23]', 'USPC 2011[34]',
       'Siena 2010[35][36]', 'C-SPAN 2009[37]', 'Times 2008[38]',
       'WSJ 2005[13]', 'Siena 2002', 'WSJ 2000', 'C-SPAN 2000',
       'Schl. 1996[5]', 'R-McI 1996[39]', 'Siena 1994', 'Siena 1990',
       'Siena 1982', 'CT 1982', 'M-B 1982', 'Schl. 1962[4]', 'Schl. 1948'],
      dtype='str')
1 Index([0, 1], dtype='int64')
2 Index(['Rank', 'Liberals (n = 190)', 'Conservatives (n = 50)'], dtype='str')
3 Index(['Seq.', 'President', 'Political party', 'Bg', 'PL', 'CAb', 'RC', 'CAp',
       'HE', 'L', 'AC', 'WR', 'EAp', 'OA', 'Im', 'DA', 'Int', 'EAb', 'FPA',
       'LA', 'IQ', 'AM', 'EV', 'O'],
      dtype='str')
4 Index(['Seq.', 'President', 'Political party', 'VSA', 'DL', 'FPL', 'MA', 'HL',
       'O'],
      dtype='str')
5 Index(['Seq.', 'President', 'Political party', 'VSA', 'DL', 'FPL', 'MA', 'HL',
       'O'],
      dtype='str')
6 Index(['Seq.', 'President', 'Political party', 'PP', 'CL', 'EM', 'MA', 'IR',
       'AS', 'RC', 'VSA', 'PEJ', 'PCT', 'O'],
      dtype='str')
7 Index(['Seq.', 'President', 'Political party', 'Bg', 'Im', 'Int', 'IQ', 'L',
       'WR', 'AC', 'EAb', 'LA', 'CAb', 'OA', 'PL', 'RC', 'CAp', 'HE', 'EAp',
       'DA', 'FPA', 'AM', 'EV', 'O'],
      dtype='str')
8 Index(['Seq.', 'President', 'Political party', 'PP', 'CL', 'EM', 'MA', 'IR',
       'AS', 'RC', 'VSA', 'PEJ', 'PCT', 'O'],
      dtype='str')
9 MultiIndex([(           'Seq.',            'Seq.'),
            (      'President',       'President'),
            ('Political party', 'Political party'),
            (     'attributes',              'Bg'),
            (     'attributes',              'Im'),
            (     'attributes',             'Int'),
            (     'attributes',              'IQ'),
            (     'attributes',               'L'),
            (     'attributes',              'WR'),
            (      'abilities',              'AC'),
            (      'abilities',             'EAb'),
            (      'abilities',              'LA'),
            (      'abilities',             'CAb'),
            (      'abilities',              'OA'),
            ('accomplishments',              'PL'),
            ('accomplishments',              'RC'),
            ('accomplishments',             'CAp'),
            ('accomplishments',              'HE'),
            ('accomplishments',             'EAp'),
            ('accomplishments',              'DA'),
            ('accomplishments',             'FPA'),
            ('accomplishments',              'AM'),
            (        'average',              'PV'),
            (        'average',               'O')],
           )
10 Index(['Rank', 'Overall (performance + diversity and inclusion score)',
       'Diversity and inclusion leadership score only'],
      dtype='str')
11 Index([0, 1], dtype='int64')
12 Index(['President', 'Outstanding', 'Above average', 'Average', 'Below average',
       'Poor', 'No opinion', 'Weighted average[a]'],
      dtype='str')
13 Index(['President', 'Outstanding', 'Above average', 'Average', 'Below average',
       'Poor', 'Weighted average[a]'],
      dtype='str')
14 Index(['President', 'Outstanding', 'Above average', 'Average', 'Below average',
       'Poor', 'Not sure', 'Weighted avg. (excl. "Not sure")'],
      dtype='str')
15 Index(['President', 'Outstanding', 'Above average', 'Average', 'Below average',
       'Poor', 'Weighted average'],
      dtype='str')
16 Index(['vteLists related to presidents and vice presidents of the United States', 'vteLists related to presidents and vice presidents of the United States.1'], dtype='str')
17 Index([0, 1], dtype='int64')
18 Index([0, 1], dtype='int64')
19 Index(['vteHistoriography', 'vteHistoriography.1'], dtype='str')
20 Index(['Historical sources', 'Historical sources.1'], dtype='str')
21 Index([0, 1], dtype='int64')
22 Index(['Fields of study', 'Fields of study.1'], dtype='str')
23 Index([0, 1], dtype='int64')
24 Index(['Methodology', 'Methodology.1'], dtype='str')
25 Index([0, 1], dtype='int64')
26 Index(['Concepts', 'Concepts.1'], dtype='str')
27 Index([0, 1], dtype='int64')
28 Index([0, 1], dtype='int64')
29 Index(['By country or region', 'By country or region.1'], dtype='str')
30 Index([0, 1], dtype='int64')
31 Index([0, 1], dtype='int64')
32 Index([0, 1], dtype='int64')
33 Index([0, 1], dtype='int64')
34 Index([0, 1], dtype='int64')
35 Index(['By war, conflict', 'By war, conflict.1'], dtype='str')
36 Index(['vteMilitary historiography', 'vteMilitary historiography.1'], dtype='str')
37 Index([0, 1], dtype='int64')
38 Index([0, 1], dtype='int64')
39 Index([0, 1], dtype='int64')
40 Index(['By person', 'By person.1'], dtype='str')
41 Index([0, 1], dtype='int64')
42 Index([0, 1], dtype='int64')
43 Index(['Other topics', 'Other topics.1'], dtype='str')
44 Index([0, 1], dtype='int64')
45 Index(['Organizations, publications', 'Organizations, publications.1'], dtype='str')
46 Index(['Related', 'Related.1'], dtype='str')

In [86]:
df = pres_dfs[0]

In [87]:
# (df
#     .iloc[1:-1]
#     .rename(columns={'Political party': 'Party'})
#     .assign(Party=lambda df_:df_
#         .Party
#         .str.replace(r'\[.*\]', '')
#         .astype('category'))
# )

In [88]:
(df
    .iloc[1:-1]
    .rename(columns={'Political party': 'Party'})
    .assign(Party=lambda df_: df_['Party']
        .str.replace(r'\[.*?\]', '', regex=True)
        .astype('category'))
)

,Seq. [b][c],President,Party,APSA 2024[27][26],Siena 2022[32],C-SPAN 2021[20],Siena 2018[33],APSA 2018[26],C-SPAN 2017[17],PHN 2016[24],...,C-SPAN 2000,Schl. 1996[5],R-McI 1996[39],Siena 1994,Siena 1990,Siena 1982,CT 1982,M-B 1982,Schl. 1962[4],Schl. 1948
1,2,John Adams,Federalist,13,16,15,14,14,19,10,...,16,11,14,12,14,10,15,9,10,9
2,3,Thomas Jefferson,Democratic-Republican,5,5,7,5,5,7,5,...,7,4,4,5,3,2,5,4,5,5
3,4,James Madison,Democratic-Republican,11,10,16,7,12,17,15,...,18,17,10,9,8,9,17,14,12,14
4,5,James Monroe,Democratic-Republican,18,12,12,8,18,13,14,...,14,15,13,15,11,15,16,15,18,12
5,6,John Quincy Adams,Democratic-Republican,20,17,17,18,23,21,17,...,19,18,18,17,16,17,19,16,13,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,42,Bill Clinton,Democratic,12,14,19,15,13,15,19,...,21,20,23,16,–,–,–,–,–,–
41,43,George W. Bush,Republican,32,35,29,33,30,33,34,...,–,–,–,–,–,–,–,–,–,–
42,44,Barack Obama,Democratic,7,11,10,17,8,12,7,...,–,–,–,–,–,–,–,–,–,–
43,45/47[b],Donald Trump,Republican,45,43,41,42,44,–,–,...,–,–,–,–,–,–,–,–,–,–
44,46,Joe Biden,Democratic,14,19,–,–,–,–,–,...,–,–,–,–,–,–,–,–,–,–

In [89]:
df.dtypes

Seq. [b][c]          string[pyarrow]
President            string[pyarrow]
Political party      string[pyarrow]
APSA 2024[27][26]     int64[pyarrow]
Siena 2022[32]        int64[pyarrow]
                          ...
Siena 1982           string[pyarrow]
CT 1982              string[pyarrow]
M-B 1982             string[pyarrow]
Schl. 1962[4]        string[pyarrow]
Schl. 1948           string[pyarrow]
Length: 28, dtype: object

In [ ]:
#### Part II